module(
    name = "ripgrep",
    version = "14.1.1",
)

bazel_dep(name = "rules_rust", version = "0.63.0")
bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "bazel_skylib", version = "1.7.1")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(edition = "2021")
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate_universe_deps = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate_universe_deps.from_cargo(
    name = "ripgrep_deps",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
        "//crates/globset:Cargo.toml",
        "//crates/grep:Cargo.toml",
        "//crates/cli:Cargo.toml",
        "//crates/matcher:Cargo.toml",
        "//crates/pcre2:Cargo.toml", 
        "//crates/printer:Cargo.toml",
        "//crates/regex:Cargo.toml",
        "//crates/searcher:Cargo.toml",
        "//crates/ignore:Cargo.toml",
    ],
)
use_repo(crate_universe_deps, "ripgrep_deps")