load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("@crate_index//:defs.bzl", "all_crate_deps")

rust_library(
    name = "ignore",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "ignore",
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/globset:globset",
    ] + all_crate_deps(
        normal = True,
    ),
)

rust_test(
    name = "lib_tests",
    crate = ":ignore",
    edition = "2021",
    deps = all_crate_deps(
        normal_dev = True,
    ),
)

rust_test(
    name = "integration_tests",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/gitignore_matched_path_or_any_parents_tests.rs",
    edition = "2021",
    deps = [
        ":ignore",
    ] + all_crate_deps(
        normal_dev = True,
    ),
)
