load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "grep_matcher",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "grep_matcher",
    edition = "2021",
    deps = [
        "@crate_index//aho-corasick",
        "@crate_index//memchr",
        "@crate_index//regex-automata",
        "@crate_index//regex-syntax",
        "@crate_index//log",
    ],
)
