load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "grep_matcher",
    srcs = [
        "src/lib.rs",
    ],
    edition = "2021",
    crate_root = "src/lib.rs",
    deps = [
        "@crate_index//:memchr",
        "@crate_index//:regex_automata",
    ],
)
