load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test", "rust_doc", "rust_clippy", "rustfmt_test")

rust_library(
    name = "grep-printer",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    crate_features = ["serde"],
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "@ripgrep_deps//:bstr",
        "@ripgrep_deps//:log",
        "@ripgrep_deps//:serde",
        "@ripgrep_deps//:serde_json",
        "@ripgrep_deps//:termcolor",
        "//crates/matcher:grep-matcher",
        "//crates/searcher:grep-searcher",
    ],
)

rust_test(
    name = "grep-printer_test",
    crate = ":grep-printer",
    edition = "2021",
    deps = [
        "//crates/regex:grep-regex",
    ],
)

rustfmt_test(
    name = "grep-printer_rustfmt_test",
    targets = [":grep-printer"],
)

rust_clippy(
    name = "grep-printer_clippy",
    deps = [":grep-printer"],
)

rust_doc(
    name = "grep-printer_doc",
    crate = ":grep-printer",
)

# Export Cargo.toml for crate_universe
exports_files(["Cargo.toml"])