load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("@crate_index//:defs.bzl", "all_crate_deps")

rust_library(
    name = "regex",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "grep_regex",
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/matcher:matcher",
    ] + all_crate_deps(
        normal = True,
    ),
)

rust_test(
    name = "lib_tests",
    crate = ":regex",
    edition = "2021",
    deps = all_crate_deps(
        normal_dev = True,
    ),
)