load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "globset",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "@crate_index//:aho-corasick",
        "@crate_index//:bstr",
        "@crate_index//:regex-automata",
        "@crate_index//:regex-syntax",
    ],
    visibility = ["//visibility:public"],
)
